BIN = hellot
CC = clang++
FLAGS = 
INC =  -I/usr/local/include -I/Users/kazumatakata/c++/glm
LIB_PATH = 
LOC_LIB = 
DYN_LIB = -lGLEW -lglfw
FRAMEWORKS = -framework Cocoa -framework OpenGL -framework IOKit
SRC = main.cpp

all:
	${CC} ${FLAGS} ${FRAMEWORKS} -g -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${DYN_LIB}